import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoutButton from "../../components/LogoutButton";
import SettingPageButton from "../../components/SettingPageButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex p-5 justify-between items-center">
        <h1 className="header text-5xl mt-5 mb-5">シフトカレンダー</h1>
        <nav className="flex items-center">
          <SettingPageButton/>
          <LogoutButton/>
        </nav>
      </div>
        {children}
      </body>
    </html>
  );
}
